on: [push]
jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps: 
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with: 
          distribution: oracle
          java-version: 17
          java-package: jdk
  run-java:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile and run Java Code
        run: |
          javac main.java
          java main
